### ISSUE TITLE
Document metaclasses

### ISSUE THREAD

**Issue by apnadkarni** [apnadkarni/ruff#48]
From RZ on the wiki:

Currently only oo::class classes and no metaclasses are recognized in
`proc ruff::private::extract_procs_and_classes` because of line :

`set class_names [[info class instances ::oo::class $pattern]]`

May be add an option -metaclasses and do an "[[info class instances $metclass ..]]".

**Comment by jakio6** [comment]
how to extract document from an oo::class? Seems there's no seperate namespace for a class and I could get a class name passed to `extrac_procs_and_classes`.

**Comment by apnadkarni** [comment]
Can you provided a simple example of what you might want to document as a test case?

**Comment by jakio6** [comment]
```tcl
package require TclOO

oo::class create the_class {
    method some_method args {
        # some method document
    }
}
```

I want to document `the_class` directly.

but
```tcl
::ruff::document {::the_class}
```
will give:
```
Namespace ::the_class does not exist.
```

**Comment by apnadkarni** [comment]
Ah, I thought you were talking about documenting metaclasses so thanks for the example. That seems like a plain old bug. I'll take a look tomorrow.

**Comment by jakio6** [comment]
I don't even know what metaclass is :rofl:

**Comment by apnadkarni** [comment]
I've uploaded 1.2.1 to the download area https://sourceforge.net/projects/magicsplat/files/ruff/

Could you please try the updated version as follows in a Tcl shell:

```
ruff::document [list ::] -include classes -output docs.html
```

and let me know if that is better. The `-include classes` option is there so you don't try to document all the global Tcl built-in commands as well.

/Ashok

**Comment by jakio6** [comment]
It works.
