### ISSUE TITLE
Spaces after leading 4 spaces not rendered as expected

### ISSUE THREAD

**Issue by apnadkarni** [apnadkarni/ruff#76]
Hi Ashok,

I wanted to create a table using pre-formatted text and noted a strange behaviour, if a line contains spaces after the first 4 spaces.

This table renders correctly (see also attached screenshot):

     | Format   | Channels | Read          |        Write         |
     |          |          | byte | short | float | byte | short | float |
     | -------------------------------------------------------------------
     | FITS     |  1       |      |       |       |      | |       |
     | FITS     |  3       |      |       |       |      | |       |

The second line of the following table does not render correctly.
It seems more than 4 spaces are removed.

     Format   | Channels | Read          |        Write         |
              |          | byte | short | float | byte | short | float |
-------------------------------------------------------------------
     FITS     |  1       |      |       |       |      | |       |
     FITS     |  3       |      |       |       |      | |       |

The documentation says:
If the line is indented 4 or more spaces, it is treated a preformatted line and passed through to the output with the first 4 spaces stripped. No other processing is done on the line.

Regards,
Paul

**Comment by apnadkarni** [comment]
Paul,

I am not able to reproduce the bug. I think github might be reformatting or something when I copied your bug report and cannot find the original. Attached screen shots show what I am getting and it looks correct. Could you please clarify.

![output](https://github.com/apnadkarni/ruff/assets/2577658/671d1dac-095f-48a3-9e1e-8f19d3dcc58a)
![rawtext](https://github.com/apnadkarni/ruff/assets/2577658/365b08b0-ada8-4881-9851-94a1bf7be158)

**Comment by apnadkarni** [comment]
See attached screenshots for what I see.

Markdown:

![markdown](https://github.com/apnadkarni/ruff/assets/2577658/a95180c0-bdee-4994-9525-0cb751d080c5)

HTML output:

![html](https://github.com/apnadkarni/ruff/assets/2577658/de441d2a-903e-487d-9fec-e74f1c08bbdc)

**Comment by PaulObermeier** [comment]
Using the attached test directory I can reproduce the error. 

[pawt.zip](https://github.com/apnadkarni/ruff/files/15210219/pawt.zip)

**Comment by apnadkarni** [comment]
I got back to revisiting this. I think the behaviour is as designed. Basically, because Tcl indentation can vary, the indentation for preformatted text is *relative to the preceding text*. Because in the bad case the table is at the same indentation as the preceding text, it is not treated as preformatted.

When you changed the indentation to be 4, it is actually less than the surrounding text. In that case, ruff assumes the normal indentation to be 0 (what else can it assume?) and so treats it as preformatted text.

Indenting the preformatted table relative to the surrounding text fixes the problem as in the attached file.

[pawtCoreBug.tcl.txt](https://github.com/user-attachments/files/17178547/pawtCoreBug.tcl.txt)

However, there is one more issue that you will see if you format the attached file. The CSS for ruff specifies a max width of 60 so the preformatted text wraps. You will need to change the option to increase or remove the max-width CSS. In some future release that could an option to ruff.

Let me know if above makes sense or not.

**Comment by PaulObermeier** [comment]
I'm fine with your explanations.
Thanks for reminding the "max-width" tag.
