### ISSUE TITLE
Fat history of changes

### ISSUE THREAD

**Issue by aplsimple** [apnadkarni/ruff#78]
Perhaps, I missed a similar issue, still it seems to be very quickly fixed, at that being so wanted.

When a procedure/method is added to Ruff list of contents, all of "Show source" links (below it) are reindexed. E.g. when you have 500 procs and add "abc" proc that happens to be 10th, all "Show source" below are referred to as 11, 12, ... 501, though old ones were 10..500. At that we have 491 changes of SCM repo history while the according procs weren't changed at all.

This results to a fat history of changes in SCM and generally messes the history. This can be seen in

https://github.com/aplsimple/aplsimple.github.io/commit/ddbfbddbfeedc6ae668309463979c8c7741cb0fe

where the changes are so big that GitHub doesn't show them and you need to click "Load diff" link (in alited.html diff box), while a real change was only _::alited::bar::Sort_ procedure inserted.

I fixed this issue by substitution of indexed links with symbolic ones. It's implemented in **AddSource** method of **formatter_html.tcl**, just using a proc name taken from _procinfo_ variable. The results are seen e.g. in
  https://aplsimple.github.io/en/tcl/alited/alited.html

Specifically, my changes are:

```
    method AddSource {source scope procname} {
        # Adds a Source code section to the document content.
        #  source - Source code fragment.
        #  scope  - The documentation scope of the content.

#        set src_id [my NewSourceId]
        set procname [string map {:: _} $procname]
        set procname [string map {: _ \" _ < _ > _ # _ $ _ ? _ ! _ . _ ( _ ) _} $procname]
        set procname [string trimleft $procname _]
        if {$procname eq {}} {set procname [my NewSourceId]}
        append Document "<div class='ruff_source'>"
        append Document "<p class='ruff_source_link'>"
        append Document "<a id='l_$procname' href=\"javascript:toggleSource('$procname')\">Show source</a>"
        append Document "</p>\n"
        append Document "<div id='$procname' class='ruff_dyn_src'><pre>[my Escape $source]</pre></div>\n"
        append Document "</div>";    # class='ruff_source'

        return
    }

```

Of course it's one of possible solutions.

**Comment by aplsimple** [comment]
Well, I used the call of **AddSource** by **AddProcedure** method of _formatter.tcl_ this way:

```
    method AddProcedure {procinfo} {
        <.....>
        if {[my Option -includesource 0] && [info exists source]} {
            my AddSource $source $scope [lindex $procinfo 5]
        }

        return

    }

```
There is another **AddSource** method in  _formatter.tcl_  along with  _formatter_html.tcl_ , I don't know why. Probably it needs an attention too.

Also, I tested adding and deleting procs / methods with updated AddSource - all works fine. Only the relevant changes enter to the repo history (in GIT at least:), no inserting / deleting others.

**Comment by apnadkarni** [comment]
Hmm, interesting, did not realize this issue. Will look at this for next release.

I've not looked at ruff for a while, being busy on other stuff so did not know this was even logged. Normally github sends me notifications on new issues for my projects, but apparently not for ruff. Probably missing some setting somewhere.

**Comment by aplsimple** [comment]
I use ancient v1.1.0, with my modification described above. It still works fine for my needs, with all of Ruff-ed stuff.

You can compare the cracked source with the original 1.1.0, both attached.
[ruff-cracked.zip](https://github.com/apnadkarni/ruff/files/14329220/ruff-cracked.zip)

**Comment by apnadkarni** [comment]
Checked in your changes for 2.4. Thanks.
