### ISSUE TITLE
package require Tk

### ISSUE THREAD

**Issue by aplsimple** [apnadkarni/ruff#79]
Ruff! requires Tcl at start:

```
package require Tcl 8.6
```

It will be fine to add Tk (or an option for this):

```
package require Tcl 8.6
package require Tk 8.6
wm withdraw .
```

...because some scripts don't use "package require Tk" command, given that a main script does it. And Ruff! can fail on such scripts if they contain some initializing code with Tk commands (e.g. customizing fonts).

**Comment by apnadkarni** [comment]
Can't you use the `-preval` option for this to load Tk or any other packages?

**Comment by aplsimple** [comment]
Tk is a specific package, not?

Your dislike of Tk is known, though why to such extent?
