### ISSUE TITLE
Release file 2.4.1 not correct

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/ruff#86]
The pkgIndex.tcl file in release file 2.4.1 contains the following line:
package ifneeded ruff 2.4b0

**Comment by apnadkarni** [comment]
Oops. Forgot I had uploaded it! Thanks, sorry.

**Comment by apnadkarni** [comment]
Now confused. Where did you see the file uploaded?

**Comment by PaulObermeier** [comment]
It is under "tags": https://github.com/apnadkarni/ruff/tags
